import { defineStore } from "pinia";
import { reactive } from "vue";

export const useUserData = defineStore("UserData", {
  state: () => ({
    firstName: "",
    secondName: "",
    thirdName: "",
    fourthName: "",
    firstNameAr: "",
    secondNameAr: "",
    thirdNameAr: "",
    fourthNameAr: "",
    dob: "",
    gender: "",
    resident: "",
    idType: "",
    idNumber: "",
    nationality: "",
    state: "",
    city: "",
    area: "",
    street: "",
    poBox: "",
    houseNumber: "",
    email: "",
    mobileNumber: "",
    branch: "",
    employersName: "",
    department: "",
    bArea: "",
    phoneNumber: "",
    bType: "",
    bSector: "",
    bTypeOther: "",
    bSectorOther: "",
    iwr: "",
    iwrOther: "",
    salary: "",
    mothersName: "",
    spouseName: "",
    maritalStatus: "",
    dateOfIssue: "",
    dateOfExpiry: "",
    cbosId: "",
    terms: "",
    terms2: "",
    atmCard: "",
    cheque: "",
  }),
});
